name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialize Node
        uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Deploy
        uses: --project gofresher-e433c
        with:
          args: deploy --only hosting:default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
