name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialize Node
        uses: actions/setup-node@master
      - name: Update React Scripts
        run: npm i react-scripts@latest
      - name: Babel Update
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: w9jds/firebase-action@v12.8.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
