name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialize Node
        uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create SA key JSON
        run: echo $GSA_KEY > "$HOME"/gcloud.json
      - name: Deploy
        uses: GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud.json firebase deploy [project specific stuff]